import { Quote } from "components/Quote";
import { useState } from "react";
import Head from "next/head";

export default function Home() {
  const [isActive, setIsActive] = useState(false);
  return (
    <div>
      <Head>
        <title>Quote App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Quote isActive={isActive} setIsActive={setIsActive} />
    </div>
  );
}
