import { Quote } from "components/Quote";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Quote App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Quote />
    </div>
  );
}
