import useSWR from "swr";
import lodash from "lodash";
import { Quote } from "components/Quote";
import Head from "next/head";
import { useState } from "react";

const fetcher = (...args) =>
  fetch(...args)
    .then((res) => res.json())
    .then(lodash.shuffle);

export default function Home() {
  const [currentQuoteIndex, setCurrentQuoteIndex] = useState(0);

  const { data: quotes, error } = useSWR("/api/quotes", fetcher);
  if (error) return <div>Failed to load</div>;
  if (!quotes) return <div>Loading...</div>;

  const currentQuote = quotes[currentQuoteIndex];

  const handleRefresh = () => {
    setCurrentQuoteIndex((prev) => {
      if (prev >= quotes.length - 1) return 0;
      return prev + 1;
    });
  };

  return (
    <div>
      <Head>
        <title>Quote App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Quote
        image={currentQuote.img}
        quote={currentQuote.quote}
        name={currentQuote.name}
        date={currentQuote.date}
        onRefreshClick={handleRefresh}
      />
    </div>
  );
}
